"""
Augment the main training dataset with DeepSeek-generated SMS that are
double-verified by a local LLaMA/Ollama model.

Workflow:
1. Load `classification_results_with_phishing_llm_balanced_with_sender.csv`.
2. For each OTP intent ensure at least `--min_per_intent` rows by generating
   new samples (is_otp=True, is_phishing=False).
3. Ensure phishing positives/negatives meet `--min_phishing_true/false`.
4. Each synthetic SMS is generated by DeepSeek *with labels* and accepted only
   if the local verifier (Ollama model) produces identical labels.
5. Append the verified rows, deduplicate by normalized text, back up the
   original CSV with a timestamp suffix, and overwrite the main file.

Environment requirements:
- `DEEPSEEK_API_KEY` in `.env`
- `OPENAI_API_KEY` in `.env`
- Optional `DEEPSEEK_MODEL`, `OPENAI_MODEL`
"""

import argparse
import json
import os
import sys
import time
import uuid
from collections import deque
from datetime import datetime
from pathlib import Path
from typing import Any, Deque, Dict, List, Optional, Tuple, Union
from urllib.parse import urlparse

import pandas as pd
import requests
from requests.exceptions import RequestException, ChunkedEncodingError
from dotenv import load_dotenv
from openai import OpenAI

load_dotenv()

ROOT_DIR = Path(__file__).resolve().parents[1]
DATA_DIR = ROOT_DIR / "data"
SOURCE_FILE = DATA_DIR / "classification_results_with_phishing_llm_balanced_with_sender.csv"
DEFAULT_CHECKPOINT = ROOT_DIR / "checkpoints" / "deepseek_augmentation_checkpoint.csv"

DEEPSEEK_API_KEY = os.getenv("DEEPSEEK_API_KEY")
DEEPSEEK_MODEL = os.getenv("DEEPSEEK_MODEL", "deepseek-chat")
DEEPSEEK_URL = os.getenv("DEEPSEEK_URL", "https://api.deepseek.com/chat/completions")

OPENAI_MODEL = os.getenv("OPENAI_MODEL", "gpt-4o-mini")
OPENAI_CLIENT = OpenAI()

OTP_INTENTS = [
    "APP_ACCOUNT_CHANGE_OTP",
    "APP_LOGIN_OTP",
    "BANK_OR_CARD_TXN_OTP",
    "DELIVERY_OR_SERVICE_OTP",
    "FINANCIAL_LOGIN_OTP",
    "GENERIC_APP_ACTION_OTP",
    "KYC_OR_ESIGN_OTP",
    "UPI_TXN_OR_PIN_OTP",
]


SAFETY_WARNING = (
    "If OTP is mentioned always include a safety reminder such as "
    "'Do not share this code'. Keep SMS length under 160 characters."
)


def normalize_text(value: str) -> str:
    return " ".join(str(value).strip().split()).lower()


def normalize_bool(value: Union[bool, str, int, None]) -> bool:
    if isinstance(value, bool):
        return value
    if value is None:
        return False
    if isinstance(value, (int, float)):
        return bool(value)
    return str(value).strip().lower() in {"true", "1", "yes"}


def ensure_bool_series(series: pd.Series) -> pd.Series:
    if series.dtype == bool:
        return series
    return series.apply(normalize_bool)


def build_retry_hint(otp_intent: str, streak: int, examples: List[str]) -> str:
    if streak < 5:
        return ""
    example_snippets = "\n".join(f"- {txt[:120]}" for txt in examples if txt)
    intent_messages = {
        "APP_ACCOUNT_CHANGE_OTP": "Describe a different app/account scenario (e.g., new brand or type of profile change) so it clearly fits APP_ACCOUNT_CHANGE_OTP.",
        "KYC_OR_ESIGN_OTP": "Mention eSign/KYC/document verification explicitly so it is labeled as KYC_OR_ESIGN_OTP.",
        "GENERIC_APP_ACTION_OTP": "Avoid login/KYC/account-change/UPI language. Pick another app action that is truly generic.",
        "FINANCIAL_LOGIN_OTP": "Reference a bank or brokerage login (NetBanking, trading app) to keep it financial.",
        "UPI_TXN_OR_PIN_OTP": "Reference UPI transactions or PIN/device linking explicitly.",
    }
    directive = intent_messages.get(
        otp_intent,
        "Vary the scenario to better match the requested intent.",
    )
    hint = (
        f"\nRetry directive: Previous {streak} attempts were rejected for repeating a similar idea. "
        f"{directive}\nRecent rejects:\n{example_snippets}"
    )
    return hint


def load_checkpoint(path: Optional[Path]) -> pd.DataFrame:
    if not path:
        return pd.DataFrame()
    path = Path(path)
    if not path.exists():
        return pd.DataFrame()
    df = pd.read_csv(path)
    if df.empty:
        return df
    df["predicted_is_otp"] = ensure_bool_series(df["predicted_is_otp"])
    df["is_phishing_original"] = ensure_bool_series(df["is_phishing_original"])
    df["classification_status"] = df.get("classification_status", "synthetic_auto")
    df["batch_number"] = df.get("batch_number", "synthetic_auto")
    print(f"Loaded {len(df)} pending rows from checkpoint: {path}")
    return df


def save_checkpoint(rows: List[Dict[str, Any]], path: Optional[Path]):
    if not path:
        return
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    pd.DataFrame(rows).to_csv(path, index=False)
    print(f"[checkpoint] Saved {len(rows)} rows to {path}")


def clear_checkpoint(path: Optional[Path]):
    if not path:
        return
    path = Path(path)
    if path.exists():
        path.unlink()
        print(f"Cleared checkpoint {path}")


def verify_deepseek_connection(timeout: int):
    parsed = urlparse(DEEPSEEK_URL)
    base_url = f"{parsed.scheme}://{parsed.netloc}"
    try:
        response = requests.get(base_url, timeout=timeout)
        print(f"DeepSeek connectivity check: HTTP {response.status_code} from {base_url}")
    except RequestException as err:
        raise RuntimeError(f"Unable to reach DeepSeek at {base_url}: {err}") from err


def call_deepseek(prompt: str, retries: int = 3, timeout: int = 120) -> Optional[Dict[str, Any]]:
    if not DEEPSEEK_API_KEY:
        raise RuntimeError("DEEPSEEK_API_KEY missing from environment")

    last_error: Optional[Exception] = None
    for attempt in range(1, retries + 1):
        try:
            response = requests.post(
                DEEPSEEK_URL,
                headers={
                    "Authorization": f"Bearer {DEEPSEEK_API_KEY}",
                    "Content-Type": "application/json",
                },
                json={
                    "model": DEEPSEEK_MODEL,
                    "messages": [
                        {
                            "role": "system",
                            "content": (
                                "You are an expert SMS generator. Always output valid JSON "
                                "and respect the requested labels."
                            ),
                        },
                        {"role": "user", "content": prompt},
                    ],
                    "temperature": 0.7,
                    "max_tokens": 1200,
                },
                timeout=timeout,
            )
            response.raise_for_status()
            content = response.json()["choices"][0]["message"]["content"].strip()
            try:
                return json.loads(content)
            except json.JSONDecodeError:
                start = content.find("{")
                end = content.rfind("}")
                if start != -1 and end != -1:
                    try:
                        return json.loads(content[start : end + 1])
                    except json.JSONDecodeError:
                        pass
            return None
        except (RequestException, ChunkedEncodingError) as err:
            last_error = err
            wait = min(8, 2 ** attempt)
            print(f"[WARN] DeepSeek request failed (attempt {attempt}/{retries}): {err}. Retrying in {wait}s...")
            time.sleep(wait)

    raise RuntimeError(f"DeepSeek request failed after {retries} attempts: {last_error}")


def call_openai(prompt: str) -> Optional[Dict[str, Any]]:
    try:
        completion = OPENAI_CLIENT.responses.create(
            model=OPENAI_MODEL,
            input=prompt,
            temperature=0.0,
            max_output_tokens=200,
        )
    except Exception as err:  # OpenAI client raises generic exceptions
        print(f"[WARN] OpenAI verifier request failed: {err}")
        return None

    text = (completion.output_text or "").strip()
    if not text:
        print("[debug] OpenAI verifier returned empty response.")
        return None
    def try_parse(payload: str) -> Optional[Dict[str, Any]]:
        try:
            return json.loads(payload)
        except json.JSONDecodeError:
            return None

    parsed = try_parse(text)
    if parsed is not None:
        return parsed

    normalized = text.strip()
    if normalized.startswith("```"):
        normalized = normalized.lstrip("`")
        if normalized.lower().startswith("json"):
            normalized = normalized[4:]
        normalized = normalized.rstrip("`")
    normalized = normalized.strip()
    start = normalized.find("{")
    end = normalized.rfind("}")
    if start != -1 and end != -1:
        snippet = normalized[start : end + 1]
        parsed = try_parse(snippet)
        if parsed is not None:
            return parsed
        print(f"[debug] Secondary JSON parse failed: {snippet}")
    else:
        print(f"[debug] Could not locate JSON object in verifier response: {text}")
    return None


def build_generation_prompt(
    is_otp: bool,
    otp_intent: str,
    is_phishing: bool,
    avoid_phrases: Optional[List[str]] = None,
    retry_hint: str = "",
) -> str:
    clarification = ""
    if otp_intent == "APP_ACCOUNT_CHANGE_OTP":
        clarification = (
            "The action must clearly describe updating or changing account profile/contact settings "
            "for an app (email/phone/password/profile)."
        )
    avoidance = ""
    if avoid_phrases:
        trimmed = [phrase[:200] for phrase in avoid_phrases if phrase]
        if trimmed:
            avoidance = "\nAvoid reusing SMS similar to:\n- " + "\n- ".join(trimmed)
    intent_rule = "\nLabel reminder: Match the OTP content to the requested intent exactly."
    if otp_intent == "KYC_OR_ESIGN_OTP":
        intent_rule = (
            "\nLabel reminder: Mention KYC, eSign, document verification, Aadhaar/PAN linking. "
            "These MUST stay `KYC_OR_ESIGN_OTP`, never generic."
        )
    elif otp_intent == "APP_ACCOUNT_CHANGE_OTP":
        intent_rule = (
            "\nLabel reminder: Describe updating profile/contact/address/password settings for an app. "
            "Always label these `APP_ACCOUNT_CHANGE_OTP`, not generic."
        )
    elif otp_intent == "GENERIC_APP_ACTION_OTP":
        intent_rule = (
            "\nLabel reminder: Use `GENERIC_APP_ACTION_OTP` only when the action is NOT login, KYC/eSign, "
            "account change, UPI, or a financial transaction."
        )
    elif otp_intent == "FINANCIAL_LOGIN_OTP":
        intent_rule = (
            "\nLabel reminder: Reference bank/financial logins (NetBanking, YONO, iMobile, brokerage platforms). "
            "Do NOT call these generic app logins."
        )
    elif otp_intent == "UPI_TXN_OR_PIN_OTP":
        intent_rule = (
            "\nLabel reminder: Mention UPI transactions, PIN/device linking, or beneficiary additions via UPI."
        )
    return f"""Generate ONE realistic SMS with these exact attributes:
- is_otp = {str(is_otp).lower()}
- otp_intent = {otp_intent}
- is_phishing = {str(is_phishing).lower()}

Rules:
- If is_otp=true, include a 4-8 digit OTP code and mention the action that matches the intent.
- If is_otp=false, otp_intent must be "NOT_OTP" and no OTP code should appear.
- If is_phishing=true, inject suspicious tone (urgent, fake rewards, shortened links).
- If is_phishing=false, keep it legitimate.
- Vary brands/apps/banks typical to India.
- {SAFETY_WARNING}
{clarification}
{intent_rule}
{avoidance}
{retry_hint}

Respond ONLY with JSON:
{{
  "sms": "...",
  "is_otp": {str(is_otp).lower()},
  "otp_intent": "{otp_intent}",
  "is_phishing": {str(is_phishing).lower()}
}}"""


def build_verification_prompt(sms: str) -> str:
    return f"""Classify the SMS using this schema and return JSON only: {{"is_otp": bool, "otp_intent": str, "is_phishing": bool}}.

Guidance (choose the *most specific* matching intent):
- `FINANCIAL_LOGIN_OTP`: OTPs for logging into banks or financial/brokerage apps (HDFC NetBanking, SBI YONO, ICICI Direct, trading platforms) when the goal is account access.
- `KYC_OR_ESIGN_OTP`: OTPs for e-signing documents, completing KYC/verification paperwork, linking PAN/Aadhaar, or document signature flows even if a bank is mentioned.
- `BANK_OR_CARD_TXN_OTP`: OTPs approving transactions (payments, transfers, card swipes).
- `APP_LOGIN_OTP`: OTPs for non-financial apps (social, ecommerce, streaming) or general “app login” with no financial keywords.
- `APP_ACCOUNT_CHANGE_OTP`: OTPs for updating app account details (email, phone, password).
- `GENERIC_APP_ACTION_OTP`: OTPs for generic actions when no other label fits.
- `UPI_TXN_OR_PIN_OTP`: OTPs for UPI transactions, linking UPI devices/PINs, or authorizing UPI payments.
- `NOT_OTP`: Messages without OTP codes.

Examples:
1. "Your HDFC NetBanking login OTP is 7428." → `FINANCIAL_LOGIN_OTP`.
2. "Use OTP 345678 to eSign your HDFC KYC form." → `KYC_OR_ESIGN_OTP`.
3. "OTP 987654 to approve ICICI Bank card transaction." → `BANK_OR_CARD_TXN_OTP`.
4. "Your UPI transaction OTP is 7842. Do not share this code." → `UPI_TXN_OR_PIN_OTP`.
5. "OTP 456789 to update your PayTM profile email." → `APP_ACCOUNT_CHANGE_OTP`.
6. "Your Swiggy login OTP is 123456." → `APP_LOGIN_OTP`.
7. "Your OTP for confirming your Ola ride rating is 8472." → `GENERIC_APP_ACTION_OTP`.
8. "Your OTP for saving a recipe on Zomato is 6185." → `GENERIC_APP_ACTION_OTP`.
9. "Your OTP for adding a Flipkart wishlist item is 7153." → `GENERIC_APP_ACTION_OTP`.

SMS: "{sms}"

Return JSON with the three fields only."""


def labels_match(a: Dict[str, Any], b: Dict[str, Any]) -> bool:
    a_is_otp = normalize_bool(a.get("is_otp"))
    b_is_otp = normalize_bool(b.get("is_otp"))
    a_intent = str(a.get("otp_intent", "")).strip()
    b_intent = str(b.get("otp_intent", "")).strip()
    if not a_is_otp:
        a_intent = "NOT_OTP"
    if not b_is_otp:
        b_intent = "NOT_OTP"
    return (
        a_is_otp == b_is_otp
        and bool(a.get("is_phishing")) == bool(b.get("is_phishing"))
        and a_intent == b_intent
    )


def generate_row(
    is_otp: bool,
    otp_intent: str,
    is_phishing: bool,
    request_timeout: int,
    debug: bool = False,
    avoid_phrases: Optional[List[str]] = None,
    retry_hint: str = "",
) -> Tuple[Optional[Dict[str, Any]], Dict[str, Any]]:
    status: Dict[str, Any] = {"reason": "unknown"}
    generation = call_deepseek(
        build_generation_prompt(
            is_otp,
            otp_intent,
            is_phishing,
            avoid_phrases=avoid_phrases,
            retry_hint=retry_hint,
        ),
        timeout=request_timeout,
    )
    if not generation:
        if debug:
            print("[debug] DeepSeek returned no JSON payload.")
        status["reason"] = "generation_failed"
        return None, status
    if "sms" not in generation:
        if debug:
            print(f"[debug] DeepSeek JSON missing 'sms' field: {generation}")
        status["reason"] = "generation_failed"
        return None, status
    verification = call_openai(build_verification_prompt(generation["sms"]))
    if not verification:
        if debug:
            print("[debug] Verifier returned no JSON.")
        status["reason"] = "verification_failed"
        return None, status
    if not labels_match(generation, verification):
        if debug:
            print(f"[debug] Labels mismatch.\n  DeepSeek: {generation}\n  Verifier: {verification}")
        status = {
            "reason": "label_mismatch",
            "generation": generation,
            "verifier": verification,
        }
        return None, status
    sms_text = " ".join(generation["sms"].strip().split())
    row = {
        "original_index": f"synthetic_{uuid.uuid4().hex[:8]}",
        "sms_text": sms_text,
        "predicted_is_otp": bool(generation["is_otp"]),
        "predicted_otp_intent": otp_intent,
        "classification_status": "synthetic_auto",
        "batch_number": "synthetic_auto",
        "is_phishing_original": bool(generation["is_phishing"]),
        "sender": "",
    }
    status["reason"] = "ok"
    return row, status


def backup_file(path: Path) -> Path:
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    backup = path.with_name(f"{path.stem}_{timestamp}{path.suffix}")
    backup.write_bytes(path.read_bytes())
    return backup


def augment_dataset(
    min_per_intent: int,
    phishing_true_min: int,
    phishing_false_min: int,
    max_attempts: int,
    checkpoint_path: Optional[Path],
    checkpoint_interval: int,
    request_timeout: int,
    connectivity_timeout: int,
    status_interval: int,
    debug: bool,
):
    if not DEEPSEEK_API_KEY:
        raise RuntimeError("DEEPSEEK_API_KEY missing from environment")
    if not os.getenv("OPENAI_API_KEY"):
        raise RuntimeError("OPENAI_API_KEY missing from environment")
    verify_deepseek_connection(connectivity_timeout)
    df = pd.read_csv(SOURCE_FILE)
    df["sms_text"] = df["sms_text"].astype(str)
    df["predicted_otp_intent"] = df["predicted_otp_intent"].astype(str)
    df["predicted_is_otp"] = ensure_bool_series(df["predicted_is_otp"])
    df["is_phishing_original"] = ensure_bool_series(df["is_phishing_original"])

    checkpoint_df = load_checkpoint(checkpoint_path)
    checkpoint_rows: List[Dict[str, Any]] = []
    if not checkpoint_df.empty:
        df = pd.concat([df, checkpoint_df], ignore_index=True)
        checkpoint_rows = checkpoint_df.to_dict("records")

    existing = {normalize_text(txt) for txt in df["sms_text"]}

    new_rows: List[Dict[str, Any]] = checkpoint_rows.copy()
    initial_checkpoint_len = len(checkpoint_rows)
    generated_since_save = 0
    completed = False

    def need_intent(intent: str) -> int:
        current = int(df[df["predicted_otp_intent"] == intent].shape[0])
        return max(0, min_per_intent - current)

    intent_needs = {intent: need_intent(intent) for intent in OTP_INTENTS}

    phishing_counts = {
        True: int(df[df["is_phishing_original"]].shape[0]),
        False: int(df[~df["is_phishing_original"]].shape[0]),
    }

    def print_plan():
        print("\n=== Augmentation Plan ===")
        for intent, remaining in intent_needs.items():
            current = int(df[df["predicted_otp_intent"] == intent].shape[0])
            target = min_per_intent
            print(f"  {intent:<25} current={current:>5} target={target:>5} remaining={remaining:>5}")
        print(
            f"\nPhishing positives: {phishing_counts[True]} / {phishing_true_min} "
            f"({'ok' if phishing_counts[True] >= phishing_true_min else 'needs more'})"
        )
        print(
            f"Phishing negatives: {phishing_counts[False]} / {phishing_false_min} "
            f"({'ok' if phishing_counts[False] >= phishing_false_min else 'needs more'})"
        )
        print(f"Max attempts: {max_attempts}, Checkpoint every {checkpoint_interval} rows\n")

    print_plan()

    needs_intents = any(v > 0 for v in intent_needs.values())
    needs_phishing = phishing_counts[True] < phishing_true_min
    if not needs_intents and not needs_phishing:
        print("Dataset already satisfies the requested targets; no augmentation needed.")
        return

    attempts = 0
    recent_dup_limit = 5
    recent_duplicates: Deque[str] = deque(maxlen=recent_dup_limit)
    duplicate_streak = 0
    mismatch_streak = 0
    mismatch_examples: Deque[str] = deque(maxlen=5)
    current_retry_hint = ""
    last_intent: Optional[str] = None

    try:
        while attempts < max_attempts and (
            any(v > 0 for v in intent_needs.values()) or phishing_counts[True] < phishing_true_min
        ):
            attempts += 1
            # Decide which scenario to target
            if any(v > 0 for v in intent_needs.values()):
                intent = max(intent_needs.items(), key=lambda item: item[1])[0]
                is_otp = True
                is_phishing = False
            else:
                intent = "NOT_OTP"
                is_otp = bool(attempts % 2)
                is_phishing = phishing_counts[True] < phishing_true_min

            if intent != last_intent:
                mismatch_streak = 0
                mismatch_examples.clear()
                current_retry_hint = ""
                last_intent = intent

            if attempts % max(1, status_interval) == 1:
                remaining = intent_needs.get(intent, 0)
                print(
                    f"[status] attempt {attempts}/{max_attempts}: intent={intent}, "
                    f"is_otp={is_otp}, is_phishing={is_phishing}, remaining_intent={remaining}"
                )

            row, result_status = generate_row(
                is_otp,
                intent,
                is_phishing,
                request_timeout,
                debug=debug,
                avoid_phrases=list(recent_duplicates),
                retry_hint=current_retry_hint,
            )
            if not row:
                reason = result_status.get("reason")
                if reason == "label_mismatch":
                    mismatch_streak += 1
                    gen_sms = result_status.get("generation", {}).get("sms")
                    if gen_sms:
                        mismatch_examples.append(gen_sms)
                    current_retry_hint = build_retry_hint(intent, mismatch_streak, list(mismatch_examples))
                else:
                    mismatch_streak = 0
                    mismatch_examples.clear()
                    current_retry_hint = ""
                if debug and reason != "label_mismatch":
                    print("[debug] No row generated; retrying same intent.")
                continue
            normalized = normalize_text(row["sms_text"])
            if normalized in existing:
                if debug:
                    print("[debug] Duplicate SMS detected; skipping.")
                recent_duplicates.append(row["sms_text"])
                duplicate_streak += 1
                if duplicate_streak >= recent_dup_limit and recent_dup_limit < 15:
                    recent_dup_limit += 2
                    recent_duplicates = deque(list(recent_duplicates), maxlen=recent_dup_limit)
                    if debug:
                        print(f"[debug] Duplicate streak {duplicate_streak}, expanding avoidance window to {recent_dup_limit}")
                continue
            existing.add(normalized)
            mismatch_streak = 0
            mismatch_examples.clear()
            current_retry_hint = ""
            duplicate_streak = 0
            new_rows.append(row)
            df = pd.concat([df, pd.DataFrame([row])], ignore_index=True)
            if intent in intent_needs and intent_needs[intent] > 0:
                intent_needs[intent] -= 1
            if row["is_phishing_original"]:
                phishing_counts[True] += 1
            else:
                phishing_counts[False] += 1

            if checkpoint_path:
                generated_since_save += 1
                if generated_since_save >= checkpoint_interval:
                    save_checkpoint(new_rows, checkpoint_path)
                    generated_since_save = 0

        if len(new_rows) == 0:
            print("No new synthetic rows were added.")
            return

        backup_path = backup_file(SOURCE_FILE)
        print(f"Backed up original dataset to {backup_path}")

        df["normalized"] = df["sms_text"].apply(normalize_text)
        df = df.drop_duplicates(subset="normalized").drop(columns="normalized")
        df.to_csv(SOURCE_FILE, index=False, encoding="utf-8-sig")
        completed = True

        print(f"Appended {len(new_rows)} verified rows. Updated dataset now has {len(df)} rows.")

    finally:
        if not checkpoint_path:
            return
        if completed:
            clear_checkpoint(checkpoint_path)
        elif len(new_rows) > initial_checkpoint_len:
            save_checkpoint(new_rows, checkpoint_path)


def parse_args():
    parser = argparse.ArgumentParser(description="Augment training dataset with DeepSeek + LLaMA verification.")
    parser.add_argument("--min_per_intent", type=int, default=1500, help="Minimum rows per OTP intent after augmentation.")
    parser.add_argument("--min_phishing_true", type=int, default=20000, help="Minimum phishing-positive rows desired.")
    parser.add_argument("--min_phishing_false", type=int, default=30000, help="Minimum phishing-negative rows desired.")
    parser.add_argument("--max_attempts", type=int, default=5000, help="Stop after this many generation attempts.")
    parser.add_argument(
        "--checkpoint_path",
        type=Path,
        default=DEFAULT_CHECKPOINT,
        help="CSV file used to checkpoint generated rows so runs can resume.",
    )
    parser.add_argument(
        "--checkpoint_interval",
        type=int,
        default=50,
        help="Save checkpoint after this many new rows are generated.",
    )
    parser.add_argument(
        "--request_timeout",
        type=int,
        default=90,
        help="Timeout (seconds) for each DeepSeek API request.",
    )
    parser.add_argument(
        "--connectivity_timeout",
        type=int,
        default=10,
        help="Timeout (seconds) for the initial DeepSeek connectivity check.",
    )
    parser.add_argument(
        "--status_interval",
        type=int,
        default=25,
        help="Print a status line every N generation attempts.",
    )
    parser.add_argument(
        "--debug",
        action="store_true",
        help="Log reasons when generated rows are rejected.",
    )
    return parser.parse_args()


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Augment training dataset with DeepSeek + LLaMA verification.")
    parser.add_argument("--min_per_intent", type=int, default=1200, help="Minimum rows per OTP intent after augmentation.")
    parser.add_argument("--min_phishing_true", type=int, default=15000, help="Minimum phishing-positive rows desired.")
    parser.add_argument("--min_phishing_false", type=int, default=25000, help="Minimum phishing-negative rows desired.")
    parser.add_argument("--max_attempts", type=int, default=4000, help="Stop after this many generation attempts.")
    parser.add_argument(
        "--checkpoint_path",
        type=Path,
        default=DEFAULT_CHECKPOINT,
        help="CSV file used to checkpoint generated rows so runs can resume.",
    )
    parser.add_argument(
        "--checkpoint_interval",
        type=int,
        default=50,
        help="Save checkpoint after this many new rows are generated.",
    )
    parser.add_argument(
        "--request_timeout",
        type=int,
        default=90,
        help="Timeout (seconds) for each DeepSeek API request.",
    )
    parser.add_argument(
        "--connectivity_timeout",
        type=int,
        default=10,
        help="Timeout (seconds) for the initial DeepSeek connectivity check.",
    )
    parser.add_argument(
        "--status_interval",
        type=int,
        default=25,
        help="Print a status line every N generation attempts.",
    )
    parser.add_argument(
        "--debug",
        action="store_true",
        help="Log reasons when generated rows are rejected.",
    )
    args = parser.parse_args()
    try:
        augment_dataset(
            min_per_intent=args.min_per_intent,
            phishing_true_min=args.min_phishing_true,
            phishing_false_min=args.min_phishing_false,
            max_attempts=args.max_attempts,
            checkpoint_path=args.checkpoint_path,
            checkpoint_interval=args.checkpoint_interval,
            request_timeout=args.request_timeout,
            connectivity_timeout=args.connectivity_timeout,
            status_interval=args.status_interval,
            debug=args.debug,
        )
    except KeyboardInterrupt:
        sys.exit("Interrupted by user")

